Fixed an Error when training L2 and SSIM models
Fixed a BUG that caused Error when training L2 and SSIM models
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [5]